AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create an S3 bucket"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "my-cloudformation-bucket-devops-pro-junction"
      AccessControl: Private # PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldObjects
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Environment
          Value: Dev
        - Key: Project
          Value: CloudFormationDemo
